version: "3"
services:
  ssl-proxy:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./certs/:/etc/nginx/certs/
    ports:
      - 80:80
      - 443:443
  website:
    image: httpd:latest
    volumes:
      - ./public:/usr/local/apache2/htdocs/
